force-app/main/default/objects/Log__c/Log__c.object-meta.xml
<CustomObject>
    <description>Object to hold error or information log, generated from various scenarios, apex code, trigger, javascript and so forth.

The Apex Class “LogUtility” is used to log records in this object.</description>
    <label>Log</label>
    <nameField>
        <displayFormat>Log-{00000}</displayFormat>
        <label>Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Log__c/fields/IsException__c.field-meta.xml
<CustomField>
    <fullName>IsException__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check if log is an exception or a notification log, check true if it is an exception/error.</description>
    <inlineHelpText>Check if log is an exception or a notification log, check true if it is an exception/error.</inlineHelpText>
    <label>IsException</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Long_Description__c.field-meta.xml
<CustomField>
    <fullName>Long_Description__c</fullName>
    <description>Log long description or message</description>
    <inlineHelpText>Log long description or message</inlineHelpText>
    <label>Long Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>Method or Function that generated the log.</description>
    <inlineHelpText>Method or Function that generated the log.</inlineHelpText>
    <label>Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <description>Class, Trigger or any point that generate the log.</description>
    <inlineHelpText>Class, Trigger or any point that generate the log.</inlineHelpText>
    <label>Origin</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Record_ID__c</fullName>
    <description>Record ID related with the log</description>
    <inlineHelpText>Record ID related with the log</inlineHelpText>
    <label>Record ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Short log description</description>
    <inlineHelpText>Short log description</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LogUtility.cls
public class LogUtility {
    
    public static void log(String title, String origin, String method, String recordId, Boolean isException, String longDescription){
        if(System.isFuture()){
            logAsync(title,origin,method,recordId,isException,longDescription);
        } else {
            logSync(title,origin,method,recordId,isException,longDescription);
        }
    }
    
    private static void logSync(String title, String origin, String method, String recordId, Boolean isException, String longDescription) {
        insert new Log__c(isException__c = isException, Long_Description__c = longDescription, Method__c = method, Origin__c = origin, Record_ID__c = recordId, Title__c = title);
    }
    
    @future
    public static void logAsync(String title, String origin, String method, String recordId, Boolean isException, String longDescription) {
        insert new Log__c(isException__c = isException, Long_Description__c = longDescription, Method__c = method, Origin__c = origin, Record_ID__c = recordId, Title__c = title);
    }
    
}